export const REGISTRO_EXISTOSO = 'REGISTRO_EXISTOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';

export const LOGINEXITOSO = 'LOGINEXITOSO';
export const LOGINERROR = 'LOGINERROR';

export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';
export const CERRAR_SESION = 'CERRAR_SESION'

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const LIMPIAR_ALERTA = 'LIMPIAR_ALERTA';

//subir archivos
export const SUBIR_ARCHIVO_EXITO = 'SUBIR_ARCHIVO_EXITO';
export const SUBIR_ARCHIVO_ERROR = 'SUBIR_ARCHIVO_ERROR';

//crear enlaces
export const CREAR_ENLACE_EXITO = 'CREAR_ENLACE_EXITO';
export const CREAR_ENLACE_ERROR = 'CREAR_ENLACE_ERROR';

export const SUBIR_ARCHIVO = 'SUBIR_ARCHIVO';

export const LIMPIAR_STATE = 'LIMPIAR_STATE';

export const AGREGAR_PASSWORD = 'AGREGAR_PASSWORD';
export const AGREGAR_DESCARGAS = 'AGREGAR_DESCARGAS';